<?php

namespace Tests\Unit;

use App\Http\Controllers\Api\LiveChatController;
use Tests\TestCase;
use Illuminate\Http\Request;

class ChatMessagesTest extends TestCase
{
	public function testCanSendChatMessage()
	{
		$this->withoutMiddleware();

		$data = [
			'message' => [
				'user' => 1,
				'message' => 'This is a test message generated by the unit test',
			],
		];

		$response = $this->postJson('/api/sendMessage', $data);
		$response->assertStatus(201)->assertJsonFragment(['message' => $data['message']['message']]);

	}

	public function test_send_chat_message_missing_user()
	{
		$this->withoutMiddleware();

		$data = [
			'message' => [
				'user' => -1,
				'message' => 'This is a test message generated by the unit test',
			],
		];

		$response = $this->postJson('/api/sendMessage', $data);
		$response->assertStatus(500);
	}

	public function test_get_messages()
	{
		$this->withoutMiddleware();

		$response = $this->getJson('/api/getMessages');
		$response->assertStatus(200)->assertJsonStructure([
			'data' => [
				'*' => [
					'user' => [
						'avatar',
						'id',
						'role_name',
						'username'
					],
					'message',
					'created_at'
				]
			]
		]);
	}
}
